[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "rtc_relay"
author = "Saul Shanabrook"
author-email = "s.shanabrook@gmail.com"
home-page = "https://github.com/jupyterlab/rtc"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
    "tornado"
]
