name: jupyter-rtc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.0.4
  - jupyter-packaging
  - nodejs=14.15.1
  - pycurl
  - rust
  - setuptools-rust
  - twine
  - yarn=1.22.5
  - nbformat
  - pytest
  - hypothesis
